name: 'Close stale issues'

on:
    schedule:
        - cron: '00 1 * * *'
    workflow_dispatch:

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v3
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  days-before-close: 7
                  days-before-stale: 0
                  only-labels: 'status: needs more info'
                  close-issue-message: 'Closing this issue because it needs more information and has not had recent activity. Please re-open this issue when more details can be provided.\n\nThanks!'
